site_name: Эстонский язык
site_url: https://get-the-manual.github.io/eesti-keel/
site_description: >-
  Здесь находятся материалы по изучению эстонского языка.

# Repository
repo_name: get-the-manual/eesti-keel
repo_url: https://github.com/get-the-manual/eesti-keel
edit_uri: edit/main/docs/

plugins:
  - search
  - autorefs
  - git-revision-date-localized:
      enable_creation_date: true
markdown_extensions:
  - attr_list
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.action.view
    - content.action.edit
  icon:
    edit: material/pencil 
    view: material/eye

extra:
  analytics:
      provider: google
      property: G-85LR0ZS5R5
  consent:
    title: Cookie consent
    description: >-
      Мы используем куки для аналитики. Нажимая “Принять”, вы
      помогаете нам улучшать документацию.

nav:
  - Главная страница: index.md
  - Обучение:
    - Kuhu? Kus? Kust?: Study/KuhuKusKust.md
  - Уровневые экзамены:
    - Общая информация: Exams/index.md
    - Сайт EIS.harno.ee: Exams/eis_harno_ee.md
    - Регистрация: Exams/registration.md
    - Информационный лист: Exams/Teabeleht-tasemeeksami-sooritajale-rus.md
    - Уровень A2:
      - Общая информация: Exams/A2/index.md
      - Требования к экзаменуемым: Exams/A2/requirements.md
      - Описание экзамена: Exams/A2/exam_description.md
      - Онлайн консультация: 
        - Общая информация: Exams/A2/OnlineConsultation/index.md
        - Инструкции по участию: Exams/A2/OnlineConsultation/Manual.md
      - Примеры заданий:
        - Kirjutamine 1: Exams/A2/Kirjutamine_1.md
        - Kirjutamine 2: Exams/A2/Kirjutamine_2.md
        - Kuulamine 1:  Exams/A2/Kuulamine_1.md
